### ISSUE TITLE
Table integer should use inclusive ranges

### ISSUE THREAD

**Issue by everilae** [gmr/pamqp#10]
https://github.com/gmr/pamqp/blob/master/pamqp/encode.py#L271 will use unnecessarily large formats for corner values of integer types and will not accept LONGLONGMIN and LONGLONGMAX at all. Given ranges should be inclusive, not exclusive as they are.

As a bonus values -32768 < value < 0 will blow up, because `short_int` is broken (see #7).

**Comment by gmr** [comment]
Addressed in 1.7.0 to be released today, thanks for the report.
