### ISSUE TITLE
Potential pamqp 3.0.0a5 codegen default issue

### ISSUE THREAD

**Issue by gmr** [gmr/pamqp#22]
Per https://github.com/Polyconseil/aioamqp/issues/216#issuecomment-598130433 it appears that there are defaults being incorrectly set where they should be None.

**Comment by eandersson** [comment]
I have the same issue I believe.
https://github.com/eandersson/amqpstorm/issues/78#issuecomment-597796839

**Comment by gmr** [comment]
This should be addressed in 3.0.0a6. Closing.
