### ISSUE TITLE
When publishing a header with number between 129-255 a 2's complement number is published

### ISSUE THREAD

**Issue by shoham-b** [gmr/pamqp#27]
This happens due to publishing the number as of type 'b' whilst type 'b' is reserved for signed bytes, hence publishing unsigned byte as signed byte.

**Comment by shubabu** [comment]
The code segments to fix are encode.table_integer and the decode equivalent

**Comment by michaelklishin** [comment]
@shoham-b if you understand the problem well and are aware of the [AMQP 0-9-1 Errata](https://www.rabbitmq.com/amqp-0-9-1-errata.html) document which is highly relevant for table data type encoding, please submit a pull request. Asking others to make a change for you is not the open source software way.

**Comment by shoham-b** [comment]
@michaelklishin agreed, and that's what I meant for. I'll do this when I can. Just a second.

**Comment by gmr** [comment]
I have a fix pending in a 3.0.0 release.

**Comment by gmr** [comment]
3.0.0 released with this issue addressed.
