### ISSUE TITLE
Add branch for 2.x releases

### ISSUE THREAD

**Issue by eandersson** [gmr/pamqp#28]
Python 2.7 is EOL, but there are still some projects using my library that are still on Python 2. Would it be possible to create a new branch to allow for pamqp 2.x updates?

**Comment by eandersson** [comment]
As an example could merge this fix from issue #24 in there https://github.com/eandersson/pamqp/commit/91b6c31d4073c177ff798896394fd9a7a52a7d6b

**Comment by gmr** [comment]
Added a `2.x` branch.
