### ISSUE TITLE
Add support for Python3.9 

### ISSUE THREAD

**Issue by erikseulean** [gmr/pamqp#34]
I noticed that Python3.9 is not mentioned here:
https://github.com/gmr/pamqp/blob/master/setup.cfg#L22

Would it be possible to add support for this version ? I'm more than happy to submit a PR.

**Comment by gmr** [comment]
I think it just works - I'll add it to setup.cfg and the tests

**Comment by gmr** [comment]
Confirmed and added, will be "official" in next release.
