### ISSUE TITLE
Too strict DOMAIN_REGEX for exchange and queue naming

### ISSUE THREAD

**Issue by deschmih** [gmr/pamqp#41]
Hi,
I am using your qamqp libray in my python app indirectly with aioamqp. Since update to aioamqp v0.15.0 I got some errors. This errors are based on DOMAIN_REGEX. I use the tag uri scheme ([tag URI scheme - Wikipedia](https://en.wikipedia.org/wiki/Tag_URI_scheme)) ([tag URI scheme - IETF](https://www.ietf.org/rfc/rfc4151.txt)) for naming exchanges and queues. This does not fit with your DOMAIN_REGEX in `pamqp/pamqp/constants.py`. 

https://github.com/gmr/pamqp/blob/main/pamqp/constants.py#L72-L76

Is there a amqp specification or convention which restrict the naming of queues and exchanges? Is it possible to enhance the DOMAIN_REGEX to meet the tag URI scheme?

Kind regards,
Michael

**Comment by michaelklishin** [comment]
@deschmih the [AMQP 0-9-1 domain/type spec](https://rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf) is incredibly vague in some areas and mentions or implies "ASCII alphanumeric values" in other cases.

RabbitMQ would accept a "tag URI" queue name and other clients do not impose any restrictions beyond name length (which can be a problem with "tag URI"s).

@gmr I think this can be relaxed. @deschmih please submit a PR with some additional tests?

**Comment by deschmih** [comment]
@michaelklishin @gmr It would be really nice to have this PR #42 soon as release available.
Thanks in advance.

**Comment by deschmih** [comment]
@gmr Is it possible to get a release or a tagged version with the latest fixes? This would help me a lot for reuse in aioamqp library. 
Thanks in advance.

**Comment by gmr** [comment]
Merged and ready for release. Will drop 3.2.0 today.
