### ISSUE TITLE
Please upload a wheel release to pypi

### ISSUE THREAD

**Issue by gilbahat** [gmr/pamqp#43]
Hi,

Please upload a wheel distribution to pypi. this makes for faster package installations. I'm not a package maintainer myself and thus can't test it but this may be a matter of simply adding 'bdist_wheel' after 'sdist' in the appropriate github action.

**Comment by gmr** [comment]
Given the package is pure-python with no compilation, I don't understand the value proposition a wheel would add. It should be equally fast as a sdist vs a wheel.

**Comment by gilbahat** [comment]
https://realpython.com/python-wheels/ claims so, but I went ahead and tested it personally:

on my machine, a 2018 macbook pro with 16GB ram:

➜  ~ time pip install pamqp
Collecting pamqp
  Using cached pamqp-3.2.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pamqp
  Building wheel for pamqp (setup.py) ... done
  Created wheel for pamqp: filename=pamqp-3.2.0-py3-none-any.whl size=33759 sha256=b5347e734f897c8db556c6d087c1aeeb1929cd5fb09d5bdab3e550f06fe7a020
  Stored in directory: /Users/gilbahat/Library/Caches/pip/wheels/b5/7d/07/cad48ab0bc49f5d08ea5d5e1b585deaf842328ab4b2c827bc6
Successfully built pamqp
Installing collected packages: pamqp
Successfully installed pamqp-3.2.0
pip install pamqp  1.50s user 0.38s system 34% cpu **5.486 total**

...
➜  ~ pip uninstall pamqp
...

➜  temp time pip install pamqp-3.2.0-py3-none-any.whl

Processing ./pamqp-3.2.0-py3-none-any.whl
Installing collected packages: pamqp
Successfully installed pamqp-3.2.0
pip install pamqp-3.2.0-py3-none-any.whl  0.61s user 0.12s system 95% cpu **0.759 total**

a lot of build systems are wasteful with reinstalls of the same package, even if they do try to cache the built wheel. then again this also means this takes room in the package cache, so.

**Comment by gmr** [comment]
Fair enough - released 3.2.1 as a sdist and wheel.
