### ISSUE TITLE
Over strict validation of queue/exchange name

### ISSUE THREAD

**Issue by shayc-code** [gmr/pamqp#47]
The library denies queue and exchange names having space character, altough it is allowed by RabbitMQ product itself.
I have legacy code in C# using EasyNetQ library,  that generates queue/exchange names by convention with space characters.
Now I write new code in Python and cannot use aio-pika or propan (which are based on pamqp) because of this limit. I see that pika library does allow spaces, but I want a more high-level and rich library.
I suggest adding space to the regexes at constants.DOMAIN_REGEX.

**Comment by andrewwhivery** [comment]
We're also having issues with queue names with spaces being invalid. 

We're using the [RabbitMQ Sharding Plugin](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_sharding), which automatically generates queue names with spaces. There's currently no way of modifying the generated queue names.

**Comment by gmr** [comment]
This is now allowed in 3.3.0
