### ISSUE TITLE
Decoded field tables have byte string keys in Python3

### ISSUE THREAD

**Issue by everilae** [gmr/pamqp#6]
Now, this could be by-design and if so, please close this issue forthwith... but:

Looking at [`_maybe_utf8`](https://github.com/gmr/pamqp/blob/master/pamqp/decode.py#L371-L377) one gets the picture that [keys would be decoded to unicode strings](https://github.com/gmr/pamqp/blob/master/pamqp/decode.py#L266), if they are utf-8 byte strings. As it turns out, this is not the case. For example:

``` python
>>> pamqp.decode.field_table(pamqp.encode.field_table({'A': 1}))
(9, {b'A': 1})
```

I think it's not quite far-fetched that this will confuse PY3 users, who have to handle encoding key values at the receiving end, or suffer `KeyError`s in order to find out that they must use bytes.

**Comment by gmr** [comment]
Addressed in 1.7, thanks!
