### ISSUE TITLE
Either wrong struct format or range for short integer encoding

### ISSUE THREAD

**Issue by everilae** [gmr/pamqp#7]
Either
- https://github.com/gmr/pamqp/blob/master/pamqp/encode.py#L177 should be 0 <= value <= 65535
- or https://github.com/gmr/pamqp/blob/master/pamqp/encode.py#L179 should be '>h' and the range -32768 <= value <= 32767

**Comment by gmr** [comment]
Is addressed in 1.7. Was conflating AMQP frame and field table behavior which led to a *stupid* regression here. Not sure if I needed sleep when I did this or what. Thanks for the report.
